# Pre-commit configuration optimized to minimize virtualenv/setuptools errors
# Uses system language where possible to avoid creating isolated environments

# Global configuration
fail_fast: false
default_language_version:
    python: python3.11

repos:
    # General hooks - use system language to avoid virtualenv issues
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
            language: system
          - id: end-of-file-fixer
            language: system
          - id: check-yaml
            language: system
          - id: check-toml
            language: system
          - id: check-merge-conflict
            language: system
          - id: check-added-large-files
            language: system

    # Python formatting - use local system installation
    - repo: local
      hooks:
          - id: black
            name: black
            entry: python -m black
            language: system
            types: [python]
            files: ^src/
            require_serial: false

    # Import sorting and cleanup - use local system installation
    - repo: local
      hooks:
          - id: isort
            name: isort
            entry: python -m isort
            language: system
            types: [python]
            args: 
              - "--profile=black"
              - "--multi-line=3"
              - "--combine-as"
              - "--remove-redundant-aliases"
              - "--force-grid-wrap=0"
            files: ^src/

    # Linting (Fast - Ruff only) - minimal scope to reduce errors
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.9
      hooks:
          - id: ruff
            args: [--fix, --select=I,F401,F811, --ignore=E501]
            files: ^src/
            fail_fast: false
          - id: ruff-format
            files: ^src/
            fail_fast: false

    # Security scanning - use local system installation
    - repo: local
      hooks:
          - id: bandit
            name: bandit
            entry: python -m bandit
            language: system
            types: [python]
            args: ["-c", "pyproject.toml", "-ll"]
            files: ^src/
            fail_fast: false

    # Conventional commits - with error tolerance
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.4.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            fail_fast: false
            verbose: false

    # Minimal formatting fallback (if other tools fail)
    - repo: local
      hooks:
          - id: basic-python-check
            name: Basic Python Syntax Check
            entry: python -m py_compile
            language: system
            files: ^src/.*\.py$
            fail_fast: false

    # Documentation linting (Uncomment for documentation linting checks)
    # - repo: https://github.com/pycqa/pydocstyle
    #   rev: 6.3.0
    #   hooks:
    #       - id: pydocstyle
    #         files: ^src/
    #         args: ["--convention=google"]

    # Conventional commits - with error tolerance
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.4.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            fail_fast: false
            verbose: false

    # Type checking (commented out due to import issues)
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v1.11.2
    #   hooks:
    #       - id: mypy
    #         additional_dependencies: [types-requests]
    #         args:
    #             [
    #                 --ignore-missing-imports,
    #                 --namespace-packages,
    #                 --explicit-package-bases,
    #             ]
    #         files: ^src/

    # Testing (commented out due to import issues)
    # - repo: local
    #   hooks:
    #     - id: pytest
    #       name: pytest
    #       entry: python -m pytest
    #       language: system
    #       pass_filenames: false
    #       args: [tests/]
    #       stages: [pre-push]
