repos:
    # General hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: check-merge-conflict
          - id: check-added-large-files

    # Python formatting
    - repo: https://github.com/psf/black
      rev: 24.8.0
      hooks:
          - id: black
            files: ^src/

    # Import sorting and cleanup
    - repo: https://github.com/pycqa/isort
      rev: 7.0.0
      hooks:
          - id: isort
            args: 
              - "--profile=black"
              - "--multi-line=3"
              - "--combine-as"
              - "--remove-redundant-aliases"
              - "--force-grid-wrap=0"
            files: ^src/

    # Linting and import fixes
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.9
      hooks:
          - id: ruff
            args: [--fix, --select=I,F401,F811]
            files: ^src/
          - id: ruff-format
            files: ^src/

    # Custom import cleanup scripts
    - repo: local
      hooks:
          - id: fix-self-imports
            name: Fix self-referential imports
            entry: powershell.exe -ExecutionPolicy Bypass -File scripts/fix-self-imports.ps1
            language: system
            files: ^src/.*\.py$
            pass_filenames: false

    # # Type checking
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v1.11.2
    #   hooks:
    #       - id: mypy
    #         additional_dependencies: [types-requests]
    #         args:
    #             [
    #                 --ignore-missing-imports,
    #                 --namespace-packages,
    #                 --explicit-package-bases,
    #             ]
    #         files: ^src/

    # Testing (commented out due to import issues)
    # - repo: local
    #   hooks:
    #     - id: pytest
    #       name: pytest
    #       entry: python -m pytest
    #       language: system
    #       pass_filenames: false
    #       args: [tests/]
    #       stages: [pre-push]
