#!/usr/bin/env powershell
# Script to clean up nbdev-generated comments

Write-Host "Cleaning up nbdev comments..." -ForegroundColor Green

# Get all Python files in src/
$pythonFiles = Get-ChildItem -Path "src" -Recurse -Filter "*.py"

$totalFiles = $pythonFiles.Count
$cleanedFiles = 0

foreach ($file in $pythonFiles) {
    $content = Get-Content $file.FullName -Raw
    $originalContent = $content

    # Remove the AUTOGENERATED header comment
    $content = $content -replace '# AUTOGENERATED! DO NOT EDIT! File to edit: [^\n]+\n', ''

    # Remove nbdev cell markers like # %% ../../nbs/path/file.ipynb 3
    $content = $content -replace '# %% \.\./\.\./nbs/[^\n]+\n', ''

    # Remove standalone # %% auto 0 comments
    $content = $content -replace '# %% auto \d+\n', ''

    # Remove empty lines that might be left after comment removal (max 2 consecutive)
    $content = $content -replace '\n\n\n+', "`n`n"

    # Clean up any leading newlines at the start of files
    $content = $content -replace '^\n+', ''

    if ($content -ne $originalContent) {
        Set-Content -Path $file.FullName -Value $content -NoNewline
        $cleanedFiles++
        Write-Host "Cleaned: $($file.Name)" -ForegroundColor Yellow
    }
}

Write-Host "Cleanup complete!" -ForegroundColor Cyan
Write-Host "Files processed: $totalFiles" -ForegroundColor White
Write-Host "Files cleaned: $cleanedFiles" -ForegroundColor Green
