#!/usr/bin/env powershell
# Enhanced script to clean up all nbdev comments

Write-Host "Enhanced nbdev comment cleanup..." -ForegroundColor Green

# Get all Python files in src/
$pythonFiles = Get-ChildItem -Path "src" -Recurse -Filter "*.py"

$totalFiles = $pythonFiles.Count
$cleanedFiles = 0

foreach ($file in $pythonFiles) {
    $lines = Get-Content $file.FullName
    $cleanedLines = @()
    $skipNextEmpty = $false

    foreach ($line in $lines) {
        $shouldKeep = $true

        # Skip nbdev-generated comments
        if ($line -match '^# AUTOGENERATED!') { $shouldKeep = $false }
        if ($line -match '^# %% \.\.\/\.\.\/nbs\/') { $shouldKeep = $false }
        if ($line -match '^# %% auto \d+$') { $shouldKeep = $false }

        # Skip empty lines immediately after removed comments
        if ($line -match '^\s*$' -and $skipNextEmpty) {
            $shouldKeep = $false
            $skipNextEmpty = $false
        }

        if ($shouldKeep) {
            $cleanedLines += $line
            $skipNextEmpty = $false
        } else {
            $skipNextEmpty = $true
        }
    }

    # Remove excessive empty lines (more than 2 consecutive)
    $finalLines = @()
    $emptyCount = 0

    foreach ($line in $cleanedLines) {
        if ($line -match '^\s*$') {
            $emptyCount++
            if ($emptyCount -le 2) {
                $finalLines += $line
            }
        } else {
            $emptyCount = 0
            $finalLines += $line
        }
    }

    # Remove leading empty lines
    while ($finalLines.Count -gt 0 -and $finalLines[0] -match '^\s*$') {
        $finalLines = $finalLines[1..($finalLines.Count-1)]
    }

    # Write back if changes were made
    $originalContent = Get-Content $file.FullName -Raw
    $newContent = $finalLines -join "`n"

    if ($originalContent -ne $newContent) {
        Set-Content -Path $file.FullName -Value $newContent -NoNewline
        $cleanedFiles++
        Write-Host "Enhanced clean: $($file.Name)" -ForegroundColor Yellow
    }
}

Write-Host "Enhanced cleanup complete!" -ForegroundColor Cyan
Write-Host "Files processed: $totalFiles" -ForegroundColor White
Write-Host "Files cleaned: $cleanedFiles" -ForegroundColor Green
