repos:
    # General hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: check-merge-conflict
          - id: check-added-large-files

    # Python formatting
    - repo: https://github.com/psf/black
      rev: 24.8.0
      hooks:
          - id: black
            files: ^src/

    # Import sorting
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: ["--profile", "black"]
            files: ^src/

    # Linting
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.9
      hooks:
          - id: ruff
            args: [--fix]
            files: ^src/
          - id: ruff-format
            files: ^src/

    # Type checking
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.2
      hooks:
          - id: mypy
            additional_dependencies: [types-requests]
            args:
                [
                    --ignore-missing-imports,
                    --namespace-packages,
                    --explicit-package-bases,
                ]
            files: ^src/

    # Testing (commented out due to import issues)
    # - repo: local
    #   hooks:
    #     - id: pytest
    #       name: pytest
    #       entry: python -m pytest
    #       language: system
    #       pass_filenames: false
    #       args: [tests/]
    #       stages: [pre-push]